// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Sources/AntaraCore/antara.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Org_Circle13_Antara_Protocol_PayloadType: SwiftProtobuf.Enum {
  public typealias RawValue = Int
  case payloadUnknown // = 0
  case payloadControl // = 1
  case payloadSync // = 2
  case payloadMessage // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .payloadUnknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .payloadUnknown
    case 1: self = .payloadControl
    case 2: self = .payloadSync
    case 3: self = .payloadMessage
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .payloadUnknown: return 0
    case .payloadControl: return 1
    case .payloadSync: return 2
    case .payloadMessage: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

}

#if swift(>=4.2)

extension Org_Circle13_Antara_Protocol_PayloadType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Org_Circle13_Antara_Protocol_PayloadType] = [
    .payloadUnknown,
    .payloadControl,
    .payloadSync,
    .payloadMessage,
  ]
}

#endif  // swift(>=4.2)

/// The outer wrapper transmitted across the transport layer
public struct Org_Circle13_Antara_Protocol_Envelope {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var version: UInt32 = 0

  /// SHA-256 hash of sender public key
  public var senderNodeID: Data = Data()

  /// SHA-256 hash of recipient public key
  public var recipientNodeID: Data = Data()

  /// Time-to-Live / Hop limit
  public var hopLimit: UInt32 = 0

  /// Ed25519 signature of payload bytes by sender_node_id
  public var signature: Data = Data()

  public var payloadType: Org_Circle13_Antara_Protocol_PayloadType = .payloadUnknown

  /// Ephemeral keys used for encrypting this segment
  public var encryptedPayload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// -------------------------------------------------------------
/// Type A: Control Payload (Unencrypted, used for routing handshake)
public struct Org_Circle13_Antara_Protocol_ControlPayload {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Org_Circle13_Antara_Protocol_ControlPayload.OneOf_Type? = nil

  public var handshakeInit: Org_Circle13_Antara_Protocol_HandshakeInit {
    get {
      if case .handshakeInit(let v)? = type {return v}
      return Org_Circle13_Antara_Protocol_HandshakeInit()
    }
    set {type = .handshakeInit(newValue)}
  }

  public var handshakeResponse: Org_Circle13_Antara_Protocol_HandshakeResponse {
    get {
      if case .handshakeResponse(let v)? = type {return v}
      return Org_Circle13_Antara_Protocol_HandshakeResponse()
    }
    set {type = .handshakeResponse(newValue)}
  }

  public var keepAlive: Org_Circle13_Antara_Protocol_KeepAlive {
    get {
      if case .keepAlive(let v)? = type {return v}
      return Org_Circle13_Antara_Protocol_KeepAlive()
    }
    set {type = .keepAlive(newValue)}
  }

  public var routeAdv: Org_Circle13_Antara_Protocol_RouteAdvertisement {
    get {
      if case .routeAdv(let v)? = type {return v}
      return Org_Circle13_Antara_Protocol_RouteAdvertisement()
    }
    set {type = .routeAdv(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable {
    case handshakeInit(Org_Circle13_Antara_Protocol_HandshakeInit)
    case handshakeResponse(Org_Circle13_Antara_Protocol_HandshakeResponse)
    case keepAlive(Org_Circle13_Antara_Protocol_KeepAlive)
    case routeAdv(Org_Circle13_Antara_Protocol_RouteAdvertisement)

  #if !swift(>=4.1)
    public static func ==(lhs: Org_Circle13_Antara_Protocol_ControlPayload.OneOf_Type, rhs: Org_Circle13_Antara_Protocol_ControlPayload.OneOf_Type) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.handshakeInit, .handshakeInit): return {
        guard case .handshakeInit(let l) = lhs, case .handshakeInit(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.handshakeResponse, .handshakeResponse): return {
        guard case .handshakeResponse(let l) = lhs, case .handshakeResponse(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.keepAlive, .keepAlive): return {
        guard case .keepAlive(let l) = lhs, case .keepAlive(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.routeAdv, .routeAdv): return {
        guard case .routeAdv(let l) = lhs, case .routeAdv(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_HandshakeInit {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Initiator ephemeral X25519 public key
  public var ephemeralKey: Data = Data()

  /// Initiator identity Ed25519 public key (encrypted)
  public var identityKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_HandshakeResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Responder ephemeral X25519 public key
  public var ephemeralKey: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_KeepAlive {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var batteryPercentage: UInt32 = 0

  public var currentQueueDepth: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_RouteAdvertisement {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var routes: [Org_Circle13_Antara_Protocol_RouteAdvertisement.RouteEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct RouteEntry {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var destinationNodeID: Data = Data()

    public var hopCount: UInt32 = 0

    public var expiresAt: UInt64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}
}

/// -------------------------------------------------------------
/// Type B: Sync Payload (Encrypted, used for CRDT Merkle DAG exchange)
public struct Org_Circle13_Antara_Protocol_SyncPayload {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Org_Circle13_Antara_Protocol_SyncPayload.OneOf_Type? = nil

  public var syncRequest: Org_Circle13_Antara_Protocol_SyncRequest {
    get {
      if case .syncRequest(let v)? = type {return v}
      return Org_Circle13_Antara_Protocol_SyncRequest()
    }
    set {type = .syncRequest(newValue)}
  }

  public var syncResponse: Org_Circle13_Antara_Protocol_SyncResponse {
    get {
      if case .syncResponse(let v)? = type {return v}
      return Org_Circle13_Antara_Protocol_SyncResponse()
    }
    set {type = .syncResponse(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Type: Equatable {
    case syncRequest(Org_Circle13_Antara_Protocol_SyncRequest)
    case syncResponse(Org_Circle13_Antara_Protocol_SyncResponse)

  #if !swift(>=4.1)
    public static func ==(lhs: Org_Circle13_Antara_Protocol_SyncPayload.OneOf_Type, rhs: Org_Circle13_Antara_Protocol_SyncPayload.OneOf_Type) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.syncRequest, .syncRequest): return {
        guard case .syncRequest(let l) = lhs, case .syncRequest(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.syncResponse, .syncResponse): return {
        guard case .syncResponse(let l) = lhs, case .syncResponse(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_SyncRequest {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of current Merkle DAG head hashes
  public var knownDagHeads: [Data] = []

  /// Bloom filter representing known message IDs
  public var bloomFilter: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_SyncResponse {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// List of messages the peer does not have
  public var missingMessages: [Org_Circle13_Antara_Protocol_MessagePayload] = []

  /// Transmitting node's DAG heads
  public var knownDagHeads: [Data] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// -------------------------------------------------------------
/// Type C: Message Payload (Encrypted end-to-end, parsed only by recipient)
public struct Org_Circle13_Antara_Protocol_MessagePayload {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// SHA-256 hash of (content + timestamp + sender)
  public var messageID: Data = Data()

  /// Unique identifier of the chat thread
  public var threadID: Data = Data()

  /// Unix epoch timestamp in milliseconds
  public var timestamp: UInt64 = 0

  /// Identity Ed25519 public key
  public var senderIdentity: Data = Data()

  /// Logical time vector clock tracking causal events
  public var vectorClock: Dictionary<String,UInt64> = [:]

  public var content: Org_Circle13_Antara_Protocol_MessagePayload.OneOf_Content? = nil

  public var textMessage: Org_Circle13_Antara_Protocol_TextMessage {
    get {
      if case .textMessage(let v)? = content {return v}
      return Org_Circle13_Antara_Protocol_TextMessage()
    }
    set {content = .textMessage(newValue)}
  }

  public var attachmentMessage: Org_Circle13_Antara_Protocol_AttachmentMessage {
    get {
      if case .attachmentMessage(let v)? = content {return v}
      return Org_Circle13_Antara_Protocol_AttachmentMessage()
    }
    set {content = .attachmentMessage(newValue)}
  }

  public var actionMessage: Org_Circle13_Antara_Protocol_ActionMessage {
    get {
      if case .actionMessage(let v)? = content {return v}
      return Org_Circle13_Antara_Protocol_ActionMessage()
    }
    set {content = .actionMessage(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Content: Equatable {
    case textMessage(Org_Circle13_Antara_Protocol_TextMessage)
    case attachmentMessage(Org_Circle13_Antara_Protocol_AttachmentMessage)
    case actionMessage(Org_Circle13_Antara_Protocol_ActionMessage)

  #if !swift(>=4.1)
    public static func ==(lhs: Org_Circle13_Antara_Protocol_MessagePayload.OneOf_Content, rhs: Org_Circle13_Antara_Protocol_MessagePayload.OneOf_Content) -> Bool {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch (lhs, rhs) {
      case (.textMessage, .textMessage): return {
        guard case .textMessage(let l) = lhs, case .textMessage(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.attachmentMessage, .attachmentMessage): return {
        guard case .attachmentMessage(let l) = lhs, case .attachmentMessage(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      case (.actionMessage, .actionMessage): return {
        guard case .actionMessage(let l) = lhs, case .actionMessage(let r) = rhs else { preconditionFailure() }
        return l == r
      }()
      default: return false
      }
    }
  #endif
  }

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_TextMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var body: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Org_Circle13_Antara_Protocol_AttachmentMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var filename: String = String()

  public var mimeType: String = String()

  public var fileSize: UInt64 = 0

  /// SHA-256 hash for verification during dynamic sync
  public var fileHash: Data = Data()

  /// Optional details
  public var metadata: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Represents edits, deletes, or custom states (CRDT operations)
public struct Org_Circle13_Antara_Protocol_ActionMessage {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var action: Org_Circle13_Antara_Protocol_ActionMessage.ActionType = .actionUnknown

  /// The ID of the message being edited/deleted
  public var targetMessageID: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum ActionType: SwiftProtobuf.Enum {
    public typealias RawValue = Int
    case actionUnknown // = 0
    case actionEdit // = 1
    case actionDelete // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .actionUnknown
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .actionUnknown
      case 1: self = .actionEdit
      case 2: self = .actionDelete
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .actionUnknown: return 0
      case .actionEdit: return 1
      case .actionDelete: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

  }

  public init() {}
}

#if swift(>=4.2)

extension Org_Circle13_Antara_Protocol_ActionMessage.ActionType: CaseIterable {
  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Org_Circle13_Antara_Protocol_ActionMessage.ActionType] = [
    .actionUnknown,
    .actionEdit,
    .actionDelete,
  ]
}

#endif  // swift(>=4.2)

#if swift(>=5.5) && canImport(_Concurrency)
extension Org_Circle13_Antara_Protocol_PayloadType: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_Envelope: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_ControlPayload: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_ControlPayload.OneOf_Type: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_HandshakeInit: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_HandshakeResponse: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_KeepAlive: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_RouteAdvertisement: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_RouteAdvertisement.RouteEntry: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_SyncPayload: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_SyncPayload.OneOf_Type: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_SyncRequest: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_SyncResponse: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_MessagePayload: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_MessagePayload.OneOf_Content: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_TextMessage: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_AttachmentMessage: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_ActionMessage: @unchecked Sendable {}
extension Org_Circle13_Antara_Protocol_ActionMessage.ActionType: @unchecked Sendable {}
#endif  // swift(>=5.5) && canImport(_Concurrency)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "org.circle13.antara.protocol"

extension Org_Circle13_Antara_Protocol_PayloadType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "PAYLOAD_UNKNOWN"),
    1: .same(proto: "PAYLOAD_CONTROL"),
    2: .same(proto: "PAYLOAD_SYNC"),
    3: .same(proto: "PAYLOAD_MESSAGE"),
  ]
}

extension Org_Circle13_Antara_Protocol_Envelope: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Envelope"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "version"),
    2: .standard(proto: "sender_node_id"),
    3: .standard(proto: "recipient_node_id"),
    4: .standard(proto: "hop_limit"),
    5: .same(proto: "signature"),
    6: .standard(proto: "payload_type"),
    7: .standard(proto: "encrypted_payload"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.version) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.senderNodeID) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.recipientNodeID) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.hopLimit) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.signature) }()
      case 6: try { try decoder.decodeSingularEnumField(value: &self.payloadType) }()
      case 7: try { try decoder.decodeSingularBytesField(value: &self.encryptedPayload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.version != 0 {
      try visitor.visitSingularUInt32Field(value: self.version, fieldNumber: 1)
    }
    if !self.senderNodeID.isEmpty {
      try visitor.visitSingularBytesField(value: self.senderNodeID, fieldNumber: 2)
    }
    if !self.recipientNodeID.isEmpty {
      try visitor.visitSingularBytesField(value: self.recipientNodeID, fieldNumber: 3)
    }
    if self.hopLimit != 0 {
      try visitor.visitSingularUInt32Field(value: self.hopLimit, fieldNumber: 4)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularBytesField(value: self.signature, fieldNumber: 5)
    }
    if self.payloadType != .payloadUnknown {
      try visitor.visitSingularEnumField(value: self.payloadType, fieldNumber: 6)
    }
    if !self.encryptedPayload.isEmpty {
      try visitor.visitSingularBytesField(value: self.encryptedPayload, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_Envelope, rhs: Org_Circle13_Antara_Protocol_Envelope) -> Bool {
    if lhs.version != rhs.version {return false}
    if lhs.senderNodeID != rhs.senderNodeID {return false}
    if lhs.recipientNodeID != rhs.recipientNodeID {return false}
    if lhs.hopLimit != rhs.hopLimit {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.payloadType != rhs.payloadType {return false}
    if lhs.encryptedPayload != rhs.encryptedPayload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_ControlPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ControlPayload"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "handshake_init"),
    2: .standard(proto: "handshake_response"),
    3: .standard(proto: "keep_alive"),
    4: .standard(proto: "route_adv"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Org_Circle13_Antara_Protocol_HandshakeInit?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .handshakeInit(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .handshakeInit(v)
        }
      }()
      case 2: try {
        var v: Org_Circle13_Antara_Protocol_HandshakeResponse?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .handshakeResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .handshakeResponse(v)
        }
      }()
      case 3: try {
        var v: Org_Circle13_Antara_Protocol_KeepAlive?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .keepAlive(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .keepAlive(v)
        }
      }()
      case 4: try {
        var v: Org_Circle13_Antara_Protocol_RouteAdvertisement?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .routeAdv(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .routeAdv(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .handshakeInit?: try {
      guard case .handshakeInit(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .handshakeResponse?: try {
      guard case .handshakeResponse(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .keepAlive?: try {
      guard case .keepAlive(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .routeAdv?: try {
      guard case .routeAdv(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_ControlPayload, rhs: Org_Circle13_Antara_Protocol_ControlPayload) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_HandshakeInit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandshakeInit"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "ephemeral_key"),
    2: .standard(proto: "identity_key"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.ephemeralKey) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.identityKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ephemeralKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralKey, fieldNumber: 1)
    }
    if !self.identityKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.identityKey, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_HandshakeInit, rhs: Org_Circle13_Antara_Protocol_HandshakeInit) -> Bool {
    if lhs.ephemeralKey != rhs.ephemeralKey {return false}
    if lhs.identityKey != rhs.identityKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_HandshakeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HandshakeResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "ephemeral_key"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.ephemeralKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ephemeralKey.isEmpty {
      try visitor.visitSingularBytesField(value: self.ephemeralKey, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_HandshakeResponse, rhs: Org_Circle13_Antara_Protocol_HandshakeResponse) -> Bool {
    if lhs.ephemeralKey != rhs.ephemeralKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_KeepAlive: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".KeepAlive"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "battery_percentage"),
    2: .standard(proto: "current_queue_depth"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.batteryPercentage) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.currentQueueDepth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.batteryPercentage != 0 {
      try visitor.visitSingularUInt32Field(value: self.batteryPercentage, fieldNumber: 1)
    }
    if self.currentQueueDepth != 0 {
      try visitor.visitSingularUInt32Field(value: self.currentQueueDepth, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_KeepAlive, rhs: Org_Circle13_Antara_Protocol_KeepAlive) -> Bool {
    if lhs.batteryPercentage != rhs.batteryPercentage {return false}
    if lhs.currentQueueDepth != rhs.currentQueueDepth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_RouteAdvertisement: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RouteAdvertisement"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "routes"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.routes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.routes.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.routes, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_RouteAdvertisement, rhs: Org_Circle13_Antara_Protocol_RouteAdvertisement) -> Bool {
    if lhs.routes != rhs.routes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_RouteAdvertisement.RouteEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Org_Circle13_Antara_Protocol_RouteAdvertisement.protoMessageName + ".RouteEntry"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "destination_node_id"),
    2: .standard(proto: "hop_count"),
    3: .standard(proto: "expires_at"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.destinationNodeID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.hopCount) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.expiresAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.destinationNodeID.isEmpty {
      try visitor.visitSingularBytesField(value: self.destinationNodeID, fieldNumber: 1)
    }
    if self.hopCount != 0 {
      try visitor.visitSingularUInt32Field(value: self.hopCount, fieldNumber: 2)
    }
    if self.expiresAt != 0 {
      try visitor.visitSingularUInt64Field(value: self.expiresAt, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_RouteAdvertisement.RouteEntry, rhs: Org_Circle13_Antara_Protocol_RouteAdvertisement.RouteEntry) -> Bool {
    if lhs.destinationNodeID != rhs.destinationNodeID {return false}
    if lhs.hopCount != rhs.hopCount {return false}
    if lhs.expiresAt != rhs.expiresAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_SyncPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncPayload"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "sync_request"),
    2: .standard(proto: "sync_response"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Org_Circle13_Antara_Protocol_SyncRequest?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .syncRequest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .syncRequest(v)
        }
      }()
      case 2: try {
        var v: Org_Circle13_Antara_Protocol_SyncResponse?
        var hadOneofValue = false
        if let current = self.type {
          hadOneofValue = true
          if case .syncResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.type = .syncResponse(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.type {
    case .syncRequest?: try {
      guard case .syncRequest(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .syncResponse?: try {
      guard case .syncResponse(let v)? = self.type else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_SyncPayload, rhs: Org_Circle13_Antara_Protocol_SyncPayload) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_SyncRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncRequest"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "known_dag_heads"),
    2: .standard(proto: "bloom_filter"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedBytesField(value: &self.knownDagHeads) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.bloomFilter) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.knownDagHeads.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.knownDagHeads, fieldNumber: 1)
    }
    if !self.bloomFilter.isEmpty {
      try visitor.visitSingularBytesField(value: self.bloomFilter, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_SyncRequest, rhs: Org_Circle13_Antara_Protocol_SyncRequest) -> Bool {
    if lhs.knownDagHeads != rhs.knownDagHeads {return false}
    if lhs.bloomFilter != rhs.bloomFilter {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_SyncResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SyncResponse"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "missing_messages"),
    2: .standard(proto: "known_dag_heads"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.missingMessages) }()
      case 2: try { try decoder.decodeRepeatedBytesField(value: &self.knownDagHeads) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.missingMessages.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.missingMessages, fieldNumber: 1)
    }
    if !self.knownDagHeads.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.knownDagHeads, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_SyncResponse, rhs: Org_Circle13_Antara_Protocol_SyncResponse) -> Bool {
    if lhs.missingMessages != rhs.missingMessages {return false}
    if lhs.knownDagHeads != rhs.knownDagHeads {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_MessagePayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MessagePayload"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .standard(proto: "message_id"),
    2: .standard(proto: "thread_id"),
    3: .same(proto: "timestamp"),
    4: .standard(proto: "sender_identity"),
    5: .standard(proto: "vector_clock"),
    6: .standard(proto: "text_message"),
    7: .standard(proto: "attachment_message"),
    8: .standard(proto: "action_message"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.messageID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.threadID) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.timestamp) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.senderIdentity) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufUInt64>.self, value: &self.vectorClock) }()
      case 6: try {
        var v: Org_Circle13_Antara_Protocol_TextMessage?
        var hadOneofValue = false
        if let current = self.content {
          hadOneofValue = true
          if case .textMessage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.content = .textMessage(v)
        }
      }()
      case 7: try {
        var v: Org_Circle13_Antara_Protocol_AttachmentMessage?
        var hadOneofValue = false
        if let current = self.content {
          hadOneofValue = true
          if case .attachmentMessage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.content = .attachmentMessage(v)
        }
      }()
      case 8: try {
        var v: Org_Circle13_Antara_Protocol_ActionMessage?
        var hadOneofValue = false
        if let current = self.content {
          hadOneofValue = true
          if case .actionMessage(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.content = .actionMessage(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.messageID.isEmpty {
      try visitor.visitSingularBytesField(value: self.messageID, fieldNumber: 1)
    }
    if !self.threadID.isEmpty {
      try visitor.visitSingularBytesField(value: self.threadID, fieldNumber: 2)
    }
    if self.timestamp != 0 {
      try visitor.visitSingularUInt64Field(value: self.timestamp, fieldNumber: 3)
    }
    if !self.senderIdentity.isEmpty {
      try visitor.visitSingularBytesField(value: self.senderIdentity, fieldNumber: 4)
    }
    if !self.vectorClock.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufUInt64>.self, value: self.vectorClock, fieldNumber: 5)
    }
    switch self.content {
    case .textMessage?: try {
      guard case .textMessage(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case .attachmentMessage?: try {
      guard case .attachmentMessage(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    }()
    case .actionMessage?: try {
      guard case .actionMessage(let v)? = self.content else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_MessagePayload, rhs: Org_Circle13_Antara_Protocol_MessagePayload) -> Bool {
    if lhs.messageID != rhs.messageID {return false}
    if lhs.threadID != rhs.threadID {return false}
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.senderIdentity != rhs.senderIdentity {return false}
    if lhs.vectorClock != rhs.vectorClock {return false}
    if lhs.content != rhs.content {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_TextMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TextMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "body"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.body) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_TextMessage, rhs: Org_Circle13_Antara_Protocol_TextMessage) -> Bool {
    if lhs.body != rhs.body {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_AttachmentMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".AttachmentMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "filename"),
    2: .standard(proto: "mime_type"),
    3: .standard(proto: "file_size"),
    4: .standard(proto: "file_hash"),
    5: .same(proto: "metadata"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.mimeType) }()
      case 3: try { try decoder.decodeSingularUInt64Field(value: &self.fileSize) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.fileHash) }()
      case 5: try { try decoder.decodeSingularBytesField(value: &self.metadata) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 1)
    }
    if !self.mimeType.isEmpty {
      try visitor.visitSingularStringField(value: self.mimeType, fieldNumber: 2)
    }
    if self.fileSize != 0 {
      try visitor.visitSingularUInt64Field(value: self.fileSize, fieldNumber: 3)
    }
    if !self.fileHash.isEmpty {
      try visitor.visitSingularBytesField(value: self.fileHash, fieldNumber: 4)
    }
    if !self.metadata.isEmpty {
      try visitor.visitSingularBytesField(value: self.metadata, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_AttachmentMessage, rhs: Org_Circle13_Antara_Protocol_AttachmentMessage) -> Bool {
    if lhs.filename != rhs.filename {return false}
    if lhs.mimeType != rhs.mimeType {return false}
    if lhs.fileSize != rhs.fileSize {return false}
    if lhs.fileHash != rhs.fileHash {return false}
    if lhs.metadata != rhs.metadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_ActionMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ActionMessage"
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    1: .same(proto: "action"),
    2: .standard(proto: "target_message_id"),
  ]

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.action) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.targetMessageID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.action != .actionUnknown {
      try visitor.visitSingularEnumField(value: self.action, fieldNumber: 1)
    }
    if !self.targetMessageID.isEmpty {
      try visitor.visitSingularBytesField(value: self.targetMessageID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Org_Circle13_Antara_Protocol_ActionMessage, rhs: Org_Circle13_Antara_Protocol_ActionMessage) -> Bool {
    if lhs.action != rhs.action {return false}
    if lhs.targetMessageID != rhs.targetMessageID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Org_Circle13_Antara_Protocol_ActionMessage.ActionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap: SwiftProtobuf._NameMap = [
    0: .same(proto: "ACTION_UNKNOWN"),
    1: .same(proto: "ACTION_EDIT"),
    2: .same(proto: "ACTION_DELETE"),
  ]
}
